import {
  Brain,
  Newspaper,
  Sun,
  Wind,
  Ticket,
  Dumbbell,
  Hospital,
  Hotel,
  Pill,
  Lightbulb,
  Package,
  BatteryCharging,
  LifeBuoy,
  CupSoda,
  Flower2,
  Dna,
  Scissors,
  Briefcase,
  Building,
  Building2,
  Bus,
  CakeSlice,
  Camera,
  Carrot,
  Cat,
  Clapperboard,
  Coffee,
  Croissant,
  Drumstick,
  Fish,
  Footprints,
  Gamepad2,
  Globe,
  GraduationCap,
  Headphones,
  House,
  Key,
  Landmark,
  Laptop,
  Luggage,
  Mail,
  Mic,
  Moon,
  Palette,
  PawPrint,
  PieChart,
  PiggyBank,
  Plane,
  Receipt,
  Rocket,
  Salad,
  Shield,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Sofa,
  Soup,
  Squirrel,
  Star,
  Store,
  Target,
  TramFront,
  TreePalm,
  TrendingDown,
  TrendingUp,
  Tv,
  UserRound,
  UtensilsCrossed,
  Watch,
  type LucideIcon,
} from 'lucide-react'

/**
 * 데이터의 emoji 필드 → lucide 아이콘 중앙 매핑.
 * 아이콘 슬롯 렌더는 전부 이 컴포넌트를 거친다 — 추후 3D 에셋 이미지로
 * 교체할 때도 이 파일 하나만 바꾸면 된다.
 */
const EMOJI_ICON: Record<string, LucideIcon> = {
  // 소비 카테고리
  '🍚': UtensilsCrossed,
  '☕️': Coffee,
  '🚌': Bus,
  '🛍️': ShoppingBag,
  '📺': Tv,
  '🎳': Gamepad2,
  '🏝️': TreePalm,
  '📈': TrendingUp,
  '💌': Mail,
  // 자산·저축
  '🏠': House,
  '💰': PiggyBank,
  '✈️': Plane,
  '🏦': Landmark,
  '🛡️': Shield,
  '🎓': GraduationCap,
  // 위시
  '🧳': Luggage,
  '🎧': Headphones,
  '📷': Camera,
  '⌚️': Watch,
  '💻': Laptop,
  // 미션·상점
  '🎯': Target,
  '🧠': Brain,
  '📉': TrendingDown,
  '🍱': Salad,
  '🥐': Croissant,
  '🏪': Store,
  '🍗': Drumstick,
  '🎬': Clapperboard,
  // 메이트 카테고리 풀
  '🍜': Soup,
  '👟': Footprints,
  '🛒': ShoppingCart,
  '💄': Palette,
  '🚇': TramFront,
  '📊': PieChart,
  '🌎': Globe,
  '🏢': Building2,
  '🚀': Rocket,
  // 피드 그룹·소득 출처
  '💼': Briefcase,
  '🧾': Receipt,
  '🏙️': Building,
  '⭐️': Star,
  '🥕': Carrot,
  '📰': Newspaper,
  // 스토리 top3 라벨
  '☀️': Sun,
  '🌬️': Wind,
  '🎫': Ticket,
  '🏋️': Dumbbell,
  '🏥': Hospital,
  '🏨': Hotel,
  '💊': Pill,
  '💡': Lightbulb,
  '📦': Package,
  '🔋': BatteryCharging,
  '🛟': LifeBuoy,
  '🥤': CupSoda,
  '🧃': CupSoda,
  '🧘': Flower2,
  '🧬': Dna,
  '🧢': Shirt,
  '🧵': Scissors,
  '🪴': Flower2,
  '💵': Landmark,
  // 아바타 (동물은 근사 아이콘)
  '🥞': CakeSlice,
  '🐿️': Squirrel,
  '👗': Shirt,
  '🎤': Mic,
  '🛋️': Sofa,
  '🌙': Moon,
  '🔑': Key,
  '🐟': Fish,
  '🐻': PawPrint,
  '🦝': Cat,
  '🙋‍♀️': UserRound,
}

interface Props {
  emoji: string
  size?: number
  className?: string
  strokeWidth?: number
}

/** 매핑된 lucide 아이콘 렌더 — 미등록 이모지는 텍스트 폴백 */
export function EmojiIcon({ emoji, size = 16, className, strokeWidth = 2 }: Props) {
  const Icon = EMOJI_ICON[emoji] ?? EMOJI_ICON[emoji.replace('️', '')] ?? EMOJI_ICON[`${emoji}️`]
  if (!Icon) return <span className={className}>{emoji}</span>
  return <Icon size={size} strokeWidth={strokeWidth} className={className} aria-hidden />
}
