import { expect, test } from '@playwright/test'

test('첫 진입에서 기존 마이 화면을 열고 다섯 탭으로 이동한다', async ({ page }) => {
  await page.goto('/')
  await expect(page).toHaveURL(/\/my$/)
  await expect(page.locator('#phone-frame')).toBeVisible()
  await expect(page.getByRole('main').last().getByRole('heading', { name: '안녕, 지혜' })).toBeVisible()
  const nav = page.getByRole('navigation')
  // AnimatePresence의 퇴장 화면이 잠시 겹치므로 마지막(현재) main에서 확인한다.
  const main = page.getByRole('main').last()
  for (const name of ['피드', '분석', '마이', '미션', '기록']) {
    await expect(nav.getByRole('link', { name, exact: true })).toBeVisible()
  }
  await nav.getByRole('link', { name: '피드', exact: true }).click()
  await expect(page).toHaveURL(/\/feed$/)
  await expect(main.getByRole('heading', { name: '오늘의 스토리' })).toBeVisible()
  await nav.getByRole('link', { name: '분석', exact: true }).click()
  await expect(page).toHaveURL(/\/insights$/)
  await expect(main.getByRole('heading', { name: 'AI 코치' })).toBeVisible()
  await nav.getByRole('link', { name: '미션', exact: true }).click()
  await expect(page).toHaveURL(/\/missions$/)
  await expect(main.getByRole('button', { name: '활동미션', exact: true })).toBeVisible()
  await main.getByRole('button', { name: '지난 내역', exact: true }).click()
  await expect(main.getByRole('heading', { name: '지난 내역' })).toBeVisible()
  await nav.getByRole('link', { name: '기록', exact: true }).click()
  await expect(page).toHaveURL(/\/diary$/)
  await expect(main.getByRole('heading', { name: '7월' })).toBeVisible()
  await nav.getByRole('link', { name: '마이', exact: true }).click()
  await expect(page).toHaveURL(/\/my$/)
  await expect(main.getByRole('heading', { name: '안녕, 지혜' })).toBeVisible()
})

test('기존 소비·저축·투자 카드와 기간 전환·공유 카드 흐름을 유지한다', async ({ page }) => {
  await page.goto('/')
  await expect(page).toHaveURL(/\/my$/)
  await expect(page.getByRole('main')).toHaveCount(1)
  await expect(page.getByText('오늘의 예산', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '주간', exact: true }).click()
  await expect(page.getByText('이번 주 예산', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '월간', exact: true }).click()
  await expect(page.getByText('7월 예산', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '저축', exact: true }).click()
  await expect(page.getByRole('button', { name: '목표', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '투자', exact: true }).click()
  await expect(page.getByRole('button', { name: '포폴', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '소비', exact: true }).click()
  await page.locator('section button').click()
  await expect(page).toHaveURL(/card=budget-monthly/)
  await expect(page.getByRole('button', { name: '공유하기' })).toBeVisible()
  await page.getByRole('button', { name: '닫기', exact: true }).click()
  await expect(page).toHaveURL(/\/my$/)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})
